"use strict";

const { stringify } = require("./yaml");

function manifestYaml(persona) {
  return stringify({
    schema: "agent-contract/v1",
    version: "0.1.0",
    persona: persona || "pragmatist",
    project: {
      stack: "./stack.yaml",
      conventions: "./conventions.yaml",
    },
    roles: [
      "./roles/generator.yaml",
      "./roles/integrator.yaml",
      "./roles/tester.yaml",
      "./roles/debugger.yaml",
      "./roles/documenter.yaml",
      "./roles/security.yaml",
    ],
    checks: {
      pre_generate: "./checks/pre-generate.sh",
      post_generate: "./checks/post-generate.sh",
      debug_scope: "./checks/debug-scope.sh",
      security_audit: "./checks/security-audit.sh",
      write_handoff: "./checks/write-handoff.sh",
      scope_check: "./checks/scope-check.sh",
    },
    templates: {
      commit: "./templates/commit.txt",
      pr: "./templates/pr.md",
      debug_report: "./templates/debug-report.md",
    },
    memory: {
      decisions: "./memory/decisions.jsonl",
    },
    enforcement: {
      checks_live_in: ["pre_post_hooks", "ci"],
      scope_violation_policy: "hard_fail",
    },
  });
}

function stackYaml(detection) {
  const body = {
    schema: "agent-contract/v1",
    generated_by: "agent-contract detect",
    confidence: detection.confidence,
    language: detection.language,
    runtime: detection.runtime,
    framework: detection.framework,
    package_manager: detection.package_manager,
    test_runner: detection.test_runner,
    build: detection.build,
    lint: detection.lint,
    formatter: detection.formatter,
    db: detection.db,
    orm: detection.orm,
    entry_points: detection.entry_points || [],
    commands: detection.commands || null,
    unresolved: detection.unresolved || [],
    evidence: detection.evidence || [],
  };
  const header =
    "# stack.yaml — generated by `agent-contract`.\n" +
    "# Edit the values; re-running detect will preserve manual overrides if you mark them.\n" +
    "# Fields under `unresolved` could not be auto-detected and SHOULD be filled in.\n\n";
  return header + stringify(body);
}

const PRESETS = {
  "oop-strict": () =>
    "# conventions.yaml — preset: oop-strict\n" +
    "# Strict OOP: constructor injection, typed exceptions, 80% coverage floor.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      module_size: { max_lines_per_file: 250, max_lines_per_function: 30, max_params: 4 },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["service_layer", "controller_layer", "repository_layer"],
        style: "arrange_act_assert",
        min_coverage: 80,
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 3,
      },
    }),

  "functional-pragmatic": () =>
    "# conventions.yaml — preset: functional-pragmatic\n" +
    "# Function-first: minimal classes, pragmatic testing, looser thresholds.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "functional",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 50, max_params: 5 },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "allowed_in_query_modules",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "function_params", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["business_logic", "api_handlers"],
        style: "arrange_act_assert",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
        ],
        n_files_threshold: 5,
      },
    }),

  "nestjs-clean-architecture": () =>
    "# conventions.yaml — preset: nestjs-clean-architecture\n" +
    "# NestJS: module/service/controller layering, DTOs, constructor DI, pipes for validation.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      framework_notes: "nestjs — modules own their domain; cross-domain via events or shared library",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 40, max_params: 4 },
      layers: {
        controller: "http boundary only — no business logic",
        service: "business logic — no direct DB access",
        repository: "data access only — no business logic",
        dto: "required for all controller inputs and service outputs",
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      validation: "class-validator pipes on all controller inputs",
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
        mocking: "jest.mock for external services; real DB for repository tests",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
          "cross_module_dependency",
        ],
        n_files_threshold: 5,
      },
    }),

  "laravel-service-pattern": () =>
    "# conventions.yaml — preset: laravel-service-pattern\n" +
    "# Laravel: thin controllers → service layer → Eloquent repositories. FormRequests for validation.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      framework_notes: "laravel — follow service pattern; keep controllers thin",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 40, max_params: 4 },
      layers: {
        controller: "delegates to service — no business logic, no direct model queries",
        service: "business logic — uses repositories or models",
        form_request: "required for all mutating controller inputs",
        model: "Eloquent only — no business logic in models",
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
        orm: "eloquent",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
        mocking: "Mockery for external services; RefreshDatabase for feature tests",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 5,
      },
    }),
};

const PERSONA_TONES = {
  architect: {
    style: "deliberate",
    ask_before_building: "always",
    documentation: "required_for_every_decision",
    prohibitions: ["ship_without_design_note", "vague_task_definitions", "shortcuts_under_time_pressure"],
  },
  vibecoder: {
    style: "fast",
    ask_before_building: "only_when_blocked",
    documentation: "inline_only",
    prohibitions: ["over_engineering", "premature_abstraction", "waiting_for_perfect_spec"],
  },
  lead: {
    style: "mentorship",
    ask_before_building: "when_design_unclear",
    documentation: "explain_the_why",
    prohibitions: ["silent_decisions", "undocumented_patterns"],
  },
  pragmatist: {
    style: "balanced",
    ask_before_building: "when_spec_is_incomplete",
    documentation: "as_needed",
    prohibitions: [],
  },
};

function conventionsYaml(preset, persona) {
  const tone = PERSONA_TONES[persona] || PERSONA_TONES.pragmatist;
  if (preset && PRESETS[preset]) {
    // Inject tone block into preset output by appending it as YAML
    return PRESETS[preset]() + "\n" + stringify({ tone });
  }
  return (
    "# conventions.yaml — declarative engineering policy.\n" +
    "# Every entry here should map to an executable check. If you can't enforce it, it doesn't belong here.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      tone,
      module_size: {
        max_lines_per_file: 300,
        max_lines_per_function: 40,
        max_params: 4,
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: {
        style: "typed_exceptions",
        bubbling: "explicit",
      },
      dependencies: {
        injection: "constructor",
        new_packages: "requires_human_approval",
      },
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 5,
      },
    })
  );
}

const PERSONA_GUIDANCE = {
  architect: {
    generator: [
      "document the design decision before writing code",
      "refuse tasks where input_shape or output_shape is undefined",
      "prefer named abstractions over anonymous lambdas or inline logic",
    ],
    debugger: [
      "trace the root cause before proposing any fix",
      "document all assumptions in the debug report",
      "if the fix touches more than 3 files, escalate to human review",
    ],
    security: [
      "document the threat model before auditing",
      "refuse to approve code with undocumented security assumptions",
      "classify each finding by OWASP category and severity before reporting",
    ],
  },
  vibecoder: {
    generator: [
      "ship working code first; iterate on structure later",
      "ask questions via code — write a prototype, not a requirements doc",
      "prefer the simplest thing that could possibly work",
    ],
    debugger: [
      "try the obvious fix first; if it works, ship it",
      "keep debug reports minimal — just the fix and a one-liner explanation",
    ],
    security: [
      "flag blockers only — skip advisory-level findings",
      "keep the report to one line per finding: file, issue, fix",
    ],
  },
  lead: {
    generator: [
      "explain the design choice in a comment on every non-obvious abstraction",
      "link to the pattern or principle that motivates each structural decision",
      "write code that a junior engineer can read without asking you",
    ],
    debugger: [
      "explain the bug in plain English before writing any code",
      "leave a note in the code explaining what caused this so the team learns",
    ],
    security: [
      "explain each finding in plain English with severity and a concrete remediation step",
      "link to the CVE, OWASP entry, or advisory that backs the finding",
      "write the report so a junior engineer can action it without asking you",
    ],
  },
  pragmatist: {
    generator: [],
    debugger: [],
    security: [],
  },
};

// Maps detected framework/language to the source and test directory globs that
// should constrain each role's may_create / may_modify. Every entry uses the
// exact label strings the detectors emit (version suffix stripped at call time).
function frameworkScopes(detection) {
  const lang = (detection && detection.language) || "";
  const fw = ((detection && detection.framework) || "").split("@")[0];

  const map = {
    // ── Node / TypeScript ────────────────────────────────────────────────────
    nestjs:     { src: ["src/**"],                                                             test: ["test/**"] },
    nextjs:     { src: ["app/**", "pages/**", "components/**", "lib/**", "styles/**", "public/**"], test: ["__tests__/**", "tests/**"] },
    remix:      { src: ["app/**"],                                                             test: ["tests/**"] },
    nuxt:       { src: ["pages/**", "components/**", "composables/**", "layouts/**", "server/**"], test: ["tests/**"] },
    sveltekit:  { src: ["src/**"],                                                             test: ["tests/**"] },
    vite:       { src: ["src/**"],                                                             test: ["tests/**"] },
    express:    { src: ["src/**", "routes/**", "middleware/**"],                               test: ["tests/**", "test/**"] },
    fastify:    { src: ["src/**", "routes/**", "plugins/**"],                                  test: ["tests/**", "test/**"] },
    koa:        { src: ["src/**", "routes/**"],                                                test: ["tests/**", "test/**"] },
    hono:       { src: ["src/**"],                                                             test: ["tests/**", "test/**"] },
    // ── PHP ──────────────────────────────────────────────────────────────────
    laravel:    { src: ["app/**", "config/**", "routes/**", "database/**", "resources/**"],   test: ["tests/**"] },
    symfony:    { src: ["src/**", "config/**", "templates/**", "migrations/**"],              test: ["tests/**"] },
    slim:       { src: ["src/**", "app/**"],                                                   test: ["tests/**"] },
    cakephp:    { src: ["src/**", "config/**", "templates/**"],                                test: ["tests/**"] },
    yii:        { src: ["models/**", "controllers/**", "views/**", "components/**"],           test: ["tests/**"] },
    // ── Python ───────────────────────────────────────────────────────────────
    django:     { src: ["apps/**", "config/**", "templates/**", "static/**"],                 test: ["tests/**"] },
    flask:      { src: ["app/**"],                                                             test: ["tests/**"] },
    fastapi:    { src: ["app/**"],                                                             test: ["tests/**"] },
    starlette:  { src: ["app/**"],                                                             test: ["tests/**"] },
    tornado:    { src: ["app/**"],                                                             test: ["tests/**"] },
    // ── Go ───────────────────────────────────────────────────────────────────
    // Go tests are co-located with source; test dirs == src dirs
    gin:        { src: ["cmd/**", "internal/**", "pkg/**", "api/**"],                         test: ["cmd/**", "internal/**", "pkg/**"] },
    echo:       { src: ["cmd/**", "internal/**", "pkg/**", "api/**"],                         test: ["cmd/**", "internal/**", "pkg/**"] },
    fiber:      { src: ["cmd/**", "internal/**", "pkg/**", "api/**"],                         test: ["cmd/**", "internal/**", "pkg/**"] },
    chi:        { src: ["cmd/**", "internal/**", "pkg/**", "api/**"],                         test: ["cmd/**", "internal/**", "pkg/**"] },
    // ── Rust ─────────────────────────────────────────────────────────────────
    axum:       { src: ["src/**"],                                                             test: ["tests/**"] },
    "actix-web":{ src: ["src/**"],                                                             test: ["tests/**"] },
    rocket:     { src: ["src/**"],                                                             test: ["tests/**"] },
    // ── Java / Kotlin ─────────────────────────────────────────────────────────
    "spring-boot": { src: ["src/main/**"],                                                    test: ["src/test/**"] },
    quarkus:    { src: ["src/main/**"],                                                        test: ["src/test/**"] },
    micronaut:  { src: ["src/main/**"],                                                        test: ["src/test/**"] },
    // ── Ruby ─────────────────────────────────────────────────────────────────
    rails:      { src: ["app/**", "config/**", "db/**", "lib/**"],                            test: ["spec/**", "test/**"] },
    sinatra:    { src: ["lib/**", "app/**"],                                                   test: ["spec/**", "test/**"] },
    // ── C# / .NET ─────────────────────────────────────────────────────────────
    aspnetcore: { src: ["Controllers/**", "Models/**", "Services/**", "Data/**", "src/**"],   test: ["tests/**", "test/**"] },
    // ── Elixir ───────────────────────────────────────────────────────────────
    phoenix:    { src: ["lib/**", "priv/**"],                                                  test: ["test/**"] },
    plug:       { src: ["lib/**"],                                                             test: ["test/**"] },
    absinthe:   { src: ["lib/**"],                                                             test: ["test/**"] },
    nerves:     { src: ["lib/**", "rootfs_overlay/**"],                                        test: ["test/**"] },
    // ── Swift ────────────────────────────────────────────────────────────────
    vapor:      { src: ["Sources/**", "App/**"],                                               test: ["Tests/**"] },
    hummingbird:{ src: ["Sources/**"],                                                         test: ["Tests/**"] },
    // ── Dart / Flutter ───────────────────────────────────────────────────────
    flutter:    { src: ["lib/**"],                                                             test: ["test/**"] },
    // ── Scala ────────────────────────────────────────────────────────────────
    akka:       { src: ["src/main/**"],                                                        test: ["src/test/**"] },
    play:       { src: ["app/**", "conf/**"],                                                  test: ["test/**"] },
    http4s:     { src: ["src/main/**"],                                                        test: ["src/test/**"] },
    zio:        { src: ["src/main/**"],                                                        test: ["src/test/**"] },
    // ── Clojure ──────────────────────────────────────────────────────────────
    compojure:  { src: ["src/**"],                                                             test: ["test/**"] },
    ring:       { src: ["src/**"],                                                             test: ["test/**"] },
    pedestal:   { src: ["src/**"],                                                             test: ["test/**"] },
    reitit:     { src: ["src/**"],                                                             test: ["test/**"] },
    // ── Deno ─────────────────────────────────────────────────────────────────
    fresh:      { src: ["routes/**", "components/**", "islands/**", "static/**"],             test: ["tests/**"] },
    oak:        { src: ["src/**"],                                                             test: ["tests/**"] },
  };

  // Language-level fallbacks when framework is absent or unrecognised
  const langFallback = {
    typescript:  { src: ["src/**", "lib/**"],          test: ["tests/**", "test/**"] },
    javascript:  { src: ["src/**", "lib/**"],          test: ["tests/**", "test/**"] },
    php:         { src: ["app/**", "src/**"],          test: ["tests/**"] },
    python:      { src: ["src/**", "app/**"],          test: ["tests/**"] },
    go:          { src: ["cmd/**", "internal/**", "pkg/**"], test: ["cmd/**", "internal/**", "pkg/**"] },
    rust:        { src: ["src/**"],                    test: ["tests/**"] },
    java:        { src: ["src/main/**"],               test: ["src/test/**"] },
    kotlin:      { src: ["src/main/**"],               test: ["src/test/**"] },
    ruby:        { src: ["lib/**", "app/**"],          test: ["spec/**", "test/**"] },
    csharp:      { src: ["src/**"],                    test: ["tests/**"] },
    elixir:      { src: ["lib/**"],                    test: ["test/**"] },
    swift:       { src: ["Sources/**"],                test: ["Tests/**"] },
    dart:        { src: ["lib/**"],                    test: ["test/**"] },
    scala:       { src: ["src/main/**"],               test: ["src/test/**"] },
    clojure:     { src: ["src/**"],                    test: ["test/**"] },
  };

  return map[fw] || langFallback[lang] || { src: ["src/**", "lib/**"], test: ["tests/**", "test/**"] };
}

function roleYaml(name, persona, detection) {
  const guidance = (PERSONA_GUIDANCE[persona] || PERSONA_GUIDANCE.pragmatist)[name] || [];
  const scopes = frameworkScopes(detection);
  const roles = {
    generator: {
      schema: "agent-contract/v1",
      role: "generator",
      persona: persona || "pragmatist",
      scope: {
        may_create: [...scopes.src, ...scopes.test],
        may_modify: [],
        may_delete: [],
      },
      inputs_required: ["feature_name", "input_shape", "output_shape", "error_cases"],
      on_missing_input: "ask",
      output: {
        must_include: ["implementation", "unit_tests"],
        must_pass: ["lint", "typecheck", "post_generate_check"],
      },
      ...(guidance.length > 0 && { guidance }),
      handoff_to: "integrator",
    },
    integrator: {
      schema: "agent-contract/v1",
      role: "integrator",
      scope: {
        may_create: [],
        may_modify: scopes.src,
        may_delete: [],
      },
      responsibility: "wire generated modules into existing app; no business logic changes",
      on_conflict: "ask",
      handoff_to: "tester",
    },
    tester: {
      schema: "agent-contract/v1",
      role: "tester",
      scope: {
        may_create: scopes.test,
        may_modify: scopes.test,
        may_delete: [],
      },
      responsibility: "add tests for uncovered paths surfaced by integrator; never modify src/",
      handoff_to: "documenter",
    },
    debugger: {
      schema: "agent-contract/v1",
      role: "debugger",
      persona: persona || "pragmatist",
      workflow: [
        "reproduce",
        "diagnose",
        "list_affected_files",
        "propose_solutions",
        "await_human_selection",
        "implement_within_scope",
      ],
      proposals: { min: 2, max: 4 },
      scope_rule: "changes_must_be_subset_of_diagnosis_files",
      refactor_policy: "forbidden_unless_explicitly_approved",
      on_ambiguity: "ask",
      ...(guidance.length > 0 && { guidance }),
      output_template: "../templates/debug-report.md",
    },
    documenter: {
      schema: "agent-contract/v1",
      role: "documenter",
      scope: {
        may_create: ["docs/**", "README.md"],
        may_modify: ["docs/**", "README.md"],
        may_delete: [],
      },
      responsibility: "update docs to reflect merged changes; never touch source or tests",
    },
    security: {
      schema: "agent-contract/v1",
      role: "security",
      persona: persona || "pragmatist",
      scope: {
        may_create: [],
        may_modify: [],
        may_delete: [],
      },
      responsibility: "audit all generated code, tests, and config for security vulnerabilities; never modify source files — emit findings only",
      audits: [
        "exposed_credentials",
        "outdated_vulnerable_dependencies",
        "insecure_code_patterns",
        "misconfigured_secrets",
        "vulnerable_config_files",
      ],
      severity_levels: ["critical", "high", "medium", "low"],
      on_finding: "hard_fail",
      check: "../checks/security-audit.sh",
      ...(guidance.length > 0 && { guidance }),
    },
  };
  return stringify(roles[name]);
}

function preGenerateCheck() {
  return `#!/usr/bin/env bash
# pre-generate.sh — gate before the generator runs.
# Hard fails if required inputs are missing.
# Warns if the codebase map is stale relative to the last git commit.
# Usage: pre-generate.sh <task-spec.json>
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"

SPEC="\${1:-}"
if [[ -z "$SPEC" || ! -f "$SPEC" ]]; then
  echo "pre-generate: missing task spec file" >&2
  exit 2
fi

required=(feature_name input_shape output_shape error_cases)
missing=()
for k in "\${required[@]}"; do
  if ! grep -q "\\"$k\\"" "$SPEC"; then
    missing+=("$k")
  fi
done

if (( \${#missing[@]} > 0 )); then
  echo "pre-generate: HARD FAIL — missing required fields: \${missing[*]}" >&2
  echo "agent must ask the human for these before proceeding." >&2
  exit 1
fi

# Codebase map freshness — warn when map predates the last commit.
# Stale map = agent navigates by outdated index; run \`agent-contract update\` to fix.
if [[ -f "$ROOT/memory/codebase-map.md" ]] && [[ -d "$PROJECT_ROOT/.git" ]]; then
  last_commit=\$(git -C "$PROJECT_ROOT" log -1 --format="%ct" 2>/dev/null || echo 0)
  map_mtime=\$(stat -c %Y "$ROOT/memory/codebase-map.md" 2>/dev/null || stat -f %m "$ROOT/memory/codebase-map.md" 2>/dev/null || echo 0)
  if (( last_commit > map_mtime )); then
    echo "pre-generate: WARNING — codebase-map.md predates the last git commit." >&2
    echo "  Run \`agent-contract update\` to refresh the index before large tasks." >&2
  fi
fi

echo "pre-generate: OK"
`;
}

function postGenerateCheck(detection) {
  const stackChecks = buildStackChecks(detection);
  const coverageCheck = buildCoverageCheck(detection);
  return `#!/usr/bin/env bash
# post-generate.sh — runs after the generator emits files.
# Checks: scope, conventions, size${stackChecks ? ", lint, typecheck, tests" : ""}${coverageCheck ? ", coverage" : ""}.
# Hard fails on any violation.
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"

# Gather changed files (empty when not a git repo)
changed=""
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  changed=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || git -C "$PROJECT_ROOT" diff --name-only || true)
fi

# Role scope check — enforce active role's declared may_create/may_modify against changed files.
if [[ -n "$changed" && -f "$ROOT/session/active-role.txt" ]]; then
  ACTIVE_ROLE=$(tr -d '[:space:]' < "$ROOT/session/active-role.txt")
  ROLE_YAML="$ROOT/roles/\${ACTIVE_ROLE}.yaml"
  if [[ -f "$ROLE_YAML" ]]; then
    allowed_role_patterns=()
    in_scope_block=0
    while IFS= read -r rl; do
      if [[ "$rl" =~ ^[[:space:]]*(may_create|may_modify)[[:space:]]*: ]]; then
        [[ "$rl" =~ \\[\\] ]] && { in_scope_block=0; continue; }
        in_scope_block=1; continue
      fi
      if [[ $in_scope_block -eq 1 ]]; then
        if [[ "$rl" =~ ^[[:space:]]*-[[:space:]]+(.+) ]]; then
          p="\${BASH_REMATCH[1]//\\\"/}"
          allowed_role_patterns+=("$p")
        else
          in_scope_block=0
        fi
      fi
    done < "$ROLE_YAML"
    if (( \${#allowed_role_patterns[@]} > 0 )); then
      while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        # Contract infrastructure is always allowed regardless of role
        case "$f" in .agent/*) continue ;; esac
        ok=0
        for pattern in "\${allowed_role_patterns[@]}"; do
          case "$f" in $pattern) ok=1; break ;; esac
        done
        if (( !ok )); then
          echo "post-generate: HARD FAIL — role '\${ACTIVE_ROLE}' scope violation: $f" >&2
          echo "  Allowed: \${allowed_role_patterns[*]}" >&2
          exit 1
        fi
      done <<< "$changed"
    fi
  fi
fi

# Scope check — discover which source dirs exist at runtime.
# Falls back to unconstrained (project root) when none are found.
if [[ -n "$changed" ]]; then
  scope_dirs=()
  for d in src app lib cmd internal pkg Sources; do
    [[ -d "$PROJECT_ROOT/$d" ]] && scope_dirs+=("$d/*")
  done
  for d in tests test spec Tests; do
    [[ -d "$PROJECT_ROOT/$d" ]] && scope_dirs+=("$d/*")
  done

  if (( \${#scope_dirs[@]} > 0 )); then
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      ok=0
      for pattern in "\${scope_dirs[@]}"; do
        case "$f" in $pattern) ok=1; break ;; esac
      done
      if (( !ok )); then
        echo "post-generate: HARD FAIL — file outside generator scope: $f" >&2
        echo "  allowed: \${scope_dirs[*]}" >&2
        exit 1
      fi
    done <<< "$changed"
  fi
fi

# Read persona from manifest.yaml (default: pragmatist).
PERSONA="pragmatist"
if [[ -f "$ROOT/manifest.yaml" ]]; then
  _p=$(grep -oE '^persona:[[:space:]]*[a-z]+' "$ROOT/manifest.yaml" | grep -oE '[a-z]+$' | head -1 || true)
  [[ -n "$_p" ]] && PERSONA="$_p"
fi

# New-package gate — hard-fail when package.json changed without a logged approval.
_np_policy=""
if [[ -f "$ROOT/conventions.yaml" ]]; then
  _np_policy=$(grep -oE 'new_packages:[[:space:]]*[a-z_]+' "$ROOT/conventions.yaml" | grep -oE '[a-z_]+$' | head -1 || true)
fi
if [[ "$_np_policy" == "requires_human_approval" && -n "$changed" ]]; then
  if printf '%s\\n' "$changed" | grep -qE '(^|/)package\\.json$'; then
    _approved=0
    if [[ -f "$ROOT/memory/decisions.jsonl" ]] && tail -10 "$ROOT/memory/decisions.jsonl" 2>/dev/null | grep -qi "approv"; then
      _approved=1
    fi
    if (( !_approved )); then
      echo "post-generate: HARD FAIL — package.json changed but no approval logged." >&2
      echo "  conventions.yaml requires human approval for new packages." >&2
      echo "  Append an approval entry to .agent/memory/decisions.jsonl before adding dependencies." >&2
      exit 1
    fi
  fi
fi

# Architect persona gate — decisions.jsonl entry required when >3 files changed.
if [[ "$PERSONA" == "architect" && -n "$changed" ]]; then
  _fc=$(printf '%s\\n' "$changed" | grep -c . || echo 0)
  if (( _fc > 3 )); then
    if [[ ! -f "$ROOT/memory/decisions.jsonl" ]] || ! tail -1 "$ROOT/memory/decisions.jsonl" 2>/dev/null | grep -q '"task"'; then
      echo "post-generate: HARD FAIL — architect persona: \${_fc} files changed with no decision logged." >&2
      echo "  Append a decisions.jsonl entry explaining the architectural decision before proceeding." >&2
      exit 1
    fi
  fi
fi

# Size check — reads max_lines_per_file from conventions.yaml (default 300).
MAX_LINES=300
if [[ -f "$ROOT/conventions.yaml" ]]; then
  _ml=$(grep -oE 'max_lines_per_file:[[:space:]]*[0-9]+' "$ROOT/conventions.yaml" | grep -oE '[0-9]+' | head -1 || true)
  [[ -n "$_ml" ]] && MAX_LINES="$_ml"
fi
if [[ -d "$PROJECT_ROOT/src" ]]; then
  while IFS= read -r f; do
    lines=$(wc -l < "$f")
    if (( lines > MAX_LINES )); then
      echo "post-generate: HARD FAIL — $f exceeds \${MAX_LINES} lines ($lines)" >&2
      exit 1
    fi
  done < <(find "$PROJECT_ROOT/src" -type f \\( -name "*.ts" -o -name "*.js" -o -name "*.php" -o -name "*.py" -o -name "*.go" \\))
fi
${stackChecks}
${coverageCheck}
echo "post-generate: OK"
`;
}

function buildStackChecks(detection) {
  if (!detection || !detection.commands) return "";
  const { commands } = detection;
  const parts = [];

  parts.push('\ncd "$PROJECT_ROOT"');

  if (commands.lint && commands.lint_ext) {
    const pat = commands.lint_ext.map((e) => `*${e}`).join("|");
    parts.push(
      `\n# Lint (${detection.lint})`,
      "lint_files=\"\"",
      "while IFS= read -r f; do",
      `  case "$f" in ${pat}) lint_files="$lint_files $f" ;; esac`,
      `done <<< "\${changed:-}"`,
      "if [[ -n \"$lint_files\" ]]; then",
      `  ${commands.lint} $lint_files || { echo "post-generate: HARD FAIL — lint (${detection.lint})" >&2; exit 1; }`,
      "fi",
    );
  }

  if (commands.typecheck) {
    parts.push(
      `\n# Typecheck (${detection.language})`,
      `${commands.typecheck} || { echo "post-generate: HARD FAIL — typecheck" >&2; exit 1; }`,
    );
  }

  if (commands.test) {
    if (commands.test_files && commands.lint_ext) {
      const pat = commands.lint_ext.map((e) => `*${e}`).join("|");
      parts.push(
        `\n# Tests (${detection.test_runner} — changed files only)`,
        "test_files=\"\"",
        "while IFS= read -r f; do",
        `  case "$f" in ${pat}) test_files="$test_files $f" ;; esac`,
        `done <<< "\${changed:-}"`,
        "if [[ -n \"$test_files\" ]]; then",
        `  ${commands.test} $test_files || { echo "post-generate: HARD FAIL — tests (${detection.test_runner})" >&2; exit 1; }`,
        "fi",
      );
    } else {
      parts.push(
        `\n# Tests (${detection.test_runner})`,
        `${commands.test} || { echo "post-generate: HARD FAIL — tests (${detection.test_runner})" >&2; exit 1; }`,
      );
    }
  }

  return parts.join("\n");
}

function buildCoverageCheck(detection) {
  const runner = detection && detection.test_runner;
  if (!runner) return "";

  let runCmd, parseCmd;
  // jacoco: opportunistic — only hard-fails when jacoco.csv is actually generated
  let jacocoNote = "";

  if (runner === "jest" || runner === "vitest") {
    runCmd = `npx ${runner} --coverage --coverageReporters=text-summary --passWithNoTests 2>&1 || true`;
    parseCmd = `printf '%s' "$_cov" | grep -oE 'Statements[[:space:]]*:[[:space:]]*[0-9]+' | grep -oE '[0-9]+$' | head -1 || echo ""`;
  } else if (runner === "pytest") {
    runCmd = `python -m pytest --cov --cov-report=term --quiet 2>&1 || true`;
    parseCmd = `printf '%s' "$_cov" | grep -E '^TOTAL' | grep -oE '[0-9]+%' | tr -d '%' | head -1 || echo ""`;
  } else if (runner === "go") {
    runCmd = `go test ./... -cover 2>&1 || true`;
    parseCmd = `printf '%s' "$_cov" | grep -oE 'coverage: [0-9.]+%' | grep -oE '[0-9.]+' | head -1 || echo ""`;
  } else if (runner === "phpunit" || runner === "pest") {
    const bin = runner === "pest" ? "./vendor/bin/pest" : "./vendor/bin/phpunit";
    runCmd = `${bin} --coverage-text --colors=never 2>&1 || true`;
    parseCmd = `printf '%s' "$_cov" | grep -oE 'Lines:[[:space:]]+[0-9]+\\.[0-9]+' | grep -oE '[0-9]+' | head -1 || echo ""`;
  } else if (runner === "junit") {
    const isMaven = detection && detection.package_manager === "maven";
    const csvPath = isMaven
      ? "target/site/jacoco/jacoco.csv"
      : "build/reports/jacoco/test/jacocoTestReport.csv";
    const testCmd = isMaven ? "mvn test -q 2>&1 || true" : "./gradlew test -q 2>&1 || true";
    // JaCoCo CSV: columns 4 (INSTRUCTION_MISSED) and 5 (INSTRUCTION_COVERED)
    jacocoNote = `  # JaCoCo must be configured in your build file — skips gracefully if CSV is absent.`;
    runCmd = testCmd;
    parseCmd = `awk -F, 'NR>1{m+=$4;c+=$5}END{if(m+c>0) printf "%.0f", c*100/(m+c)}' ${csvPath} 2>/dev/null || echo ""`;
  } else {
    return "";
  }

  const lines = [
    "",
    "# Coverage gate — reads min_coverage from conventions.yaml; skipped for vibecoder persona.",
    "_min_cov=\"\"",
    "if [[ -f \"$ROOT/conventions.yaml\" ]]; then",
    "  _min_cov=$(grep -oE 'min_coverage:[[:space:]]*[0-9]+' \"$ROOT/conventions.yaml\" | grep -oE '[0-9]+' | head -1 || true)",
    "fi",
    `if [[ -n "$_min_cov" && "\${PERSONA:-pragmatist}" != "vibecoder" ]]; then`,
  ];
  if (jacocoNote) lines.push(jacocoNote);
  lines.push(
    `  _cov=$(${runCmd})`,
    `  _stmts=$(${parseCmd})`,
    `  if [[ -n "$_stmts" ]] && (( \${_stmts%.*} < _min_cov )); then`,
    `    echo "post-generate: HARD FAIL — coverage \${_stmts}% is below min_coverage \${_min_cov}%" >&2`,
    "    exit 1",
    "  fi",
    "fi",
  );
  return lines.join("\n");
}

function debugScopeCheck() {
  return `#!/usr/bin/env bash
# debug-scope.sh — enforces "fix, don't refactor" rule.
# Compares proposed changes against the file list in the debug report.
# Hard fails if changes touch files outside the diagnosed scope.
set -euo pipefail

REPORT="\${1:-}"
if [[ -z "$REPORT" || ! -f "$REPORT" ]]; then
  echo "debug-scope: missing debug report" >&2
  exit 2
fi

# Extract files listed under "## Affected Files" in the report.
declared=$(awk '
  /^## Affected Files/ { in_section=1; next }
  /^## / && in_section { in_section=0 }
  in_section && /^- / { print substr($0, 3) }
' "$REPORT" | sed 's/:.*//')

if [[ -z "$declared" ]]; then
  echo "debug-scope: HARD FAIL — no affected files declared in report" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
changed=$(git -C "$PROJECT_ROOT" diff --name-only 2>/dev/null || true)

violations=()
while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  if ! grep -qxF "$f" <<< "$declared"; then
    violations+=("$f")
  fi
done <<< "$changed"

if (( \${#violations[@]} > 0 )); then
  echo "debug-scope: HARD FAIL — changes outside diagnosed scope:" >&2
  printf '  %s\\n' "\${violations[@]}" >&2
  echo "Either expand the diagnosis (and re-justify) or remove these changes." >&2
  exit 1
fi

echo "debug-scope: OK"
`;
}

function securityAuditCheck() {
  return `#!/usr/bin/env bash
# security-audit.sh — run by the security role after code generation.
# Scans for exposed credentials, insecure patterns, and vulnerable dependencies.
# Hard fails on any critical or high-severity finding.
# Compatible with bash 3.x (macOS default).
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"

FAIL=0

# Gather changed/staged files (fall back to all tracked files outside .agent/)
changed=""
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  changed=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || git -C "$PROJECT_ROOT" diff --name-only || true)
fi
if [[ -z "\${changed:-}" ]]; then
  changed=$(git -C "$PROJECT_ROOT" ls-files 2>/dev/null | grep -v '^.agent/' || true)
fi

# ── 1. Exposed credentials ────────────────────────────────────────────────────
CRED_PATTERNS=(
  'password\\s*=\\s*["'"'"'][^"'"'"']{4,}'
  'api_?key\\s*=\\s*["'"'"'][^"'"'"']{8,}'
  'secret\\s*=\\s*["'"'"'][^"'"'"']{8,}'
  'token\\s*=\\s*["'"'"'][^"'"'"']{8,}'
  'private_?key\\s*=\\s*["'"'"'][^"'"'"']{8,}'
  'AUTH_TOKEN\\s*=\\s*[^$\\n][^\\n]{4,}'
  'AWS_SECRET_ACCESS_KEY\\s*=\\s*[^$\\n][^\\n]{4,}'
  'BEGIN (RSA|EC|OPENSSH|PGP) PRIVATE KEY'
)

while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  [[ ! -f "$PROJECT_ROOT/$f" ]] && continue
  # Skip example/documentation files — they contain placeholder variable names only
  case "$f" in
    *.md|*.example|*.txt|.env.example|.env.*.example) continue ;;
    .agents/*|.claude/*|.cursor/*|.agent/*) continue ;;
  esac
  for pat in "\${CRED_PATTERNS[@]}"; do
    if grep -qiE "$pat" "$PROJECT_ROOT/$f" 2>/dev/null; then
      echo "security-audit: HARD FAIL — possible credential in $f (pattern: $pat)" >&2
      FAIL=1
    fi
  done
done <<< "\${changed:-}"

# ── 2. .env files committed to git (excluding .env.example templates) ─────────
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  tracked_env=$(git -C "$PROJECT_ROOT" ls-files | grep -E '^\\.env$|^\\.env\\.[^e][^x]' || true)
  if [[ -n "$tracked_env" ]]; then
    echo "security-audit: HARD FAIL — .env file(s) tracked by git:" >&2
    echo "$tracked_env" | sed 's/^/  /' >&2
    FAIL=1
  fi
fi

# ── 3. Insecure code patterns (bash 3.x-compatible: parallel arrays) ──────────
INSECURE_KEYS=(
  "eval("
  "innerHTML "
  "dangerouslySetInnerHTML"
  "shell=True"
  "os.system("
  "MD5("
  "Math.random()"
)
INSECURE_MSGS=(
  "dangerous eval — arbitrary code execution risk"
  "innerHTML assignment — XSS risk; use textContent or a sanitiser"
  "React dangerouslySetInnerHTML — XSS risk"
  "subprocess shell=True — command injection risk"
  "os.system — command injection risk; use subprocess with a list"
  "MD5 for hashing — not collision-resistant; use SHA-256 or better"
  "Math.random — not cryptographically secure; use crypto.getRandomValues"
)

while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  [[ ! -f "$PROJECT_ROOT/$f" ]] && continue
  case "$f" in
    *.js|*.ts|*.jsx|*.tsx|*.py|*.php|*.rb|*.go|*.java|*.cs) ;;
    *) continue ;;
  esac
  i=0
  while [[ $i -lt \${#INSECURE_KEYS[@]} ]]; do
    if grep -qF "\${INSECURE_KEYS[$i]}" "$PROJECT_ROOT/$f" 2>/dev/null; then
      echo "security-audit: WARNING — $f: \${INSECURE_MSGS[$i]}" >&2
    fi
    i=$((i + 1))
  done
done <<< "\${changed:-}"

# ── 4. Dependency vulnerability scan ─────────────────────────────────────────
if [[ -f "$PROJECT_ROOT/package.json" ]] && command -v npm &>/dev/null; then
  echo "security-audit: running npm audit..."
  npm_audit_json=$(npm audit --json 2>/dev/null || true)
  critical=$(echo "$npm_audit_json" | grep -oE '"critical":[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1 || echo 0)
  high=$(echo "$npm_audit_json" | grep -oE '"high":[[:space:]]*[0-9]+' | grep -oE '[0-9]+' | head -1 || echo 0)
  critical=\${critical:-0}
  high=\${high:-0}
  if (( critical + high > 0 )); then
    echo "security-audit: HARD FAIL — \${critical} critical and \${high} high npm vulnerabilities; run \\\`npm audit\\\` for details" >&2
    FAIL=1
  fi
fi

if [[ -f "$PROJECT_ROOT/requirements.txt" ]] && command -v safety &>/dev/null; then
  echo "security-audit: running safety check..."
  safety check -r "$PROJECT_ROOT/requirements.txt" || {
    echo "security-audit: HARD FAIL — vulnerable Python dependencies detected" >&2
    FAIL=1
  }
fi

if (( FAIL )); then
  echo "security-audit: HARD FAIL — resolve all critical findings above before merging." >&2
  exit 1
fi

echo "security-audit: OK"
`;
}

function commitTemplate() {
  return `<type>(<scope>): <subject>

<body>

Refs: <ticket>
Agent: <role> via agent-contract
`;
}

function prTemplate() {
  return `## What changed

<one-paragraph summary>

## Why

<link to ticket, decision log entry, or context>

## Scope

- [ ] Changes confined to declared scope
- [ ] No new dependencies (or: dependency approved in decisions.jsonl)
- [ ] No schema changes (or: migration included)

## Checks

- [ ] pre-generate / debug-scope passed
- [ ] post-generate passed
- [ ] Tests added / updated
- [ ] Docs updated if behavior changed

## Decision trail

<paste the relevant decisions.jsonl entry, if any>
`;
}

function debugReportTemplate() {
  return `# Debug Report

## Symptom
<observed behavior, exact error, conditions to reproduce>

## Reproduction
1.
2.

## Diagnosis
<root cause in plain language; reference specific lines>

## Affected Files
- path/to/file.ts:42-58
- path/to/other.ts:10-22

## Proposed Solutions
1. **<short label>** — <description>. Trade-off: <what it costs>.
2. **<short label>** — <description>. Trade-off: <what it costs>.

## Selected Solution
<filled in after human selects; the agent must wait>

## Implementation Notes
<filled in during implementation; must stay within Affected Files>
`;
}

function readmeForAgentDir() {
  return `# .agent/

Deterministic contract layer for coding agents. This directory is the **single source of truth** for how AI agents operate in this repository.

Any agent (Claude, Codex, Copilot, Antigravity, etc.) entering this repo MUST:

1. Read \`manifest.yaml\` first.
2. Load \`stack.yaml\` to understand the technology context.
3. Load \`conventions.yaml\` to understand engineering rules.
4. Load the relevant role from \`roles/\` for the current task.
5. Run the appropriate check from \`checks/\` before and after generating output.
6. Append non-trivial decisions to \`memory/decisions.jsonl\`.

Humans: see \`conventions.yaml\` to change policy. Re-run \`agent-contract init\` after dependency changes to refresh \`stack.yaml\`.
`;
}

function shimContent() {
  return `<!-- agent-contract:shim -->
# Agent Contract — ALWAYS ACTIVE

This repository enforces a deterministic agent contract. The contract is **non-optional** and applies to every session, every task, every model. It does not need to be mentioned in the prompt — it is always in effect.

## Boot Sequence — Run at the Start of EVERY Session

1. Check \`.agent/memory/\` for any \`handoff-*.md\` files. If found, read the most recent before proceeding.
2. Read \`.agent/manifest.yaml\` to load the full contract.
3. Read \`.agent/memory/codebase-map.md\` — use this as your index. Do NOT read raw source files before consulting the map.
4. Load the relevant role from \`.agent/roles/<role>.yaml\` for the current task.
5. Run \`.agent/checks/pre-generate.sh\` before generating any code.
6. Write your active role name (e.g. \`generator\`) to \`.agent/session/active-role.txt\` — one word, no whitespace. This enables the scope-enforcement hook.

## Enforcement Rules

- Scope violations **hard-fail**. Only touch files within the declared task scope.
- When inputs are missing or ambiguous, **ask the human** — do not assume or fill in defaults.
- \`refactor_policy: forbidden_unless_explicitly_approved\` — fix only what was asked.
- Log every non-trivial decision to \`.agent/memory/decisions.jsonl\`.

## Session Handoff Protocol

When a task is **completely done** (checks pass, decisions logged):

1. Copy \`.agent/templates/handoff.md\` to \`.agent/memory/handoff-YYYY-MM-DD-HHMM.md\`.
2. **Auto-populate** Role, Files Changed, and Last 5 Decisions by running the commands shown in the template comments.
3. **Write only** the Summary, Blockers, and Next Steps sections yourself — one paragraph, one list of blockers, one bullet list.
4. Tell the user: "Task complete. Start a fresh session and open \`.agent/memory/handoff-<timestamp>.md\` to continue."

Handoff notes are the only continuity guarantee across sessions. Always write one at task completion.
<!-- /agent-contract:shim -->
`;
}

function handoffTemplate() {
  return `# Handoff — {{YYYY-MM-DD-HHMM}}

<!-- ═══ AUTO-POPULATE: run each command and paste the output ═══ -->
## Role
<!-- cat .agent/session/active-role.txt -->

## Files Changed
<!-- git diff --name-only HEAD || git diff --name-only --cached -->

## Last 5 Decisions
<!-- tail -5 .agent/memory/decisions.jsonl -->

<!-- ═══ MODEL-FILL: write only these three sections ═══ -->
## Summary
<!-- One paragraph. What was accomplished and why. No vague language. -->

## Blockers
<!-- List any unresolved issues. Write "none" if clean. -->

## Next Steps
<!-- Bullet list. Each item: specific file or action, and why it comes next. -->

---
## Resume Prompt
\`\`\`
Resuming from handoff {{YYYY-MM-DD-HHMM}}. Role: {{ROLE}}.
Boot: .agent/memory/codebase-map.md → .agent/memory/decisions.jsonl → this file.
Next: {{paste Next Steps bullets here}}
\`\`\`
`;
}

function conventionsDraftYaml(inferences) {
  const { sample_size, style, errors, naming, tests } = inferences;
  const lines = [];

  lines.push("# conventions.draft.yaml — DRAFT generated by `agent-contract learn`.");
  lines.push(`# Sampled ${sample_size} source file(s). Review each field then merge into conventions.yaml.`);
  lines.push("# Delete this file after merging.");
  lines.push("#");
  lines.push('schema: "agent-contract/v1"');
  lines.push("");

  // Paradigm
  if (style) {
    lines.push(`# paradigm — inferred (confidence: ${style.confidence})`);
    lines.push(`# evidence: ${style.evidence.class_files} class file(s), ${style.evidence.func_files} function-only file(s)`);
    lines.push(`paradigm: ${style.paradigm}`);
  } else {
    lines.push("# paradigm — could not infer; set manually: oop | functional | mixed");
    lines.push("paradigm: oop");
  }
  lines.push("");

  lines.push("module_size:");
  lines.push("  max_lines_per_file: 300    # default — not inferred");
  lines.push("  max_lines_per_function: 40");
  lines.push("  max_params: 4");
  lines.push("");

  lines.push("db:");
  lines.push("  transactions: required_for_multi_write");
  lines.push("  migrations: required_for_schema_change");
  lines.push("  raw_queries: forbidden_outside_repository_layer");
  lines.push("");

  // Errors
  if (errors && errors.style !== "unstructured") {
    lines.push(`# errors.style — inferred (confidence: ${errors.confidence})`);
    lines.push(`# evidence: ${errors.evidence.try_catch_files} file(s) with try/catch, ${errors.evidence.custom_error_classes} custom error class(es)`);
    lines.push("errors:");
    lines.push(`  style: ${errors.style}`);
    lines.push("  bubbling: explicit");
  } else {
    lines.push("errors:");
    lines.push("  style: typed_exceptions    # default — could not infer");
    lines.push("  bubbling: explicit");
  }
  lines.push("");

  lines.push("dependencies:");
  lines.push("  injection: constructor");
  lines.push("  new_packages: requires_human_approval");
  lines.push("");

  // Testing
  if (tests) {
    lines.push(`# testing.style — inferred (confidence: ${tests.confidence})`);
    if (tests.evidence) lines.push(`# evidence: ${tests.evidence.spec_files} spec file(s) found`);
    lines.push("testing:");
    lines.push("  required_for:");
    lines.push("  - service_layer");
    lines.push("  - controller_layer");
    lines.push(`  style: ${tests.pattern}`);
  } else {
    lines.push("testing:");
    lines.push("  required_for:");
    lines.push("  - service_layer");
    lines.push("  - controller_layer");
    lines.push("  style: arrange_act_assert    # default — no test files found");
  }
  lines.push("");

  // Naming — shown as a commented suggestion since conventions.yaml has no naming key by default
  if (naming) {
    lines.push(`# naming — inferred (confidence: ${naming.confidence})`);
    const ev = Object.entries(naming.evidence).map(([k, v]) => `${k}: ${v}`).join(", ");
    lines.push(`# evidence: ${ev}`);
    lines.push("# Uncomment to enforce:");
    lines.push("# naming:");
    lines.push(`#   files: ${naming.convention}`);
    lines.push("");
  }

  lines.push("clarification:");
  lines.push("  ask_when:");
  lines.push("  - spec_missing_input_shape");
  lines.push("  - spec_missing_error_behavior");
  lines.push("  - touching_more_than_n_files");
  lines.push("  - new_external_dependency");
  lines.push("  - schema_change");
  lines.push("  n_files_threshold: 5");

  return lines.join("\n") + "\n";
}

function configYaml() {
  return [
    "# .agent/config.yaml — orchestrator configuration.",
    "# Uncomment and set values to override the defaults.",
    "#",
    "# Providers (auto-detected in this order if not set):",
    "#   anthropic   — requires ANTHROPIC_API_KEY (api.anthropic.com, billed per token)",
    "#   openai      — requires OPENAI_API_KEY (api.openai.com, billed per token)",
    "#   claude-code — uses your Claude Pro/Max subscription via the installed `claude` CLI.",
    "#                 No API key needed. Requires Claude Code to be installed.",
    "#   echo        — dry-run only; prints the assembled prompt, calls nothing.",
    "#",
    "# If none of the above is configured, auto-detection picks the first available option.",
    "#",
    "# model: override the model used by the provider (optional).",
    "#   anthropic default: claude-opus-4-8",
    "#   openai default:    gpt-4o",
    "#   claude-code:       controlled by your Claude Code settings, not this field.",
    "#",
    "# Environment variables always take precedence over this file:",
    "#   AGENT_PROVIDER, AGENT_MODEL, ANTHROPIC_API_KEY, OPENAI_API_KEY",
    "",
    "# provider: claude-code",
    "# model: claude-opus-4-8",
  ].join("\n") + "\n";
}

function decisionsHeader() {
  // JSONL files start empty; we put a comment-style first line that JSON parsers will skip
  // because consumers should read line-by-line and skip non-JSON lines.
  return "";
}

function handoffNote({ role, task, provider, model, usage, recentDecisions, reason }) {
  const ts = new Date().toISOString();
  const { total, limit, pct } = usage;
  const totalFmt = total.toLocaleString();
  const limitFmt = limit.toLocaleString();
  const isCompletion = reason === "completion";

  const decisionLines = (recentDecisions || [])
    .slice(-5)
    .map((d) => `- [${d.ts}] ${d.role}: ${d.task} (${d.output_lines} output lines)`)
    .join("\n") || "  (no prior decisions in this session)";

  return [
    `# Agent Handoff — ${ts}`,
    "",
    isCompletion
      ? `> This handoff was generated automatically when the task completed successfully.`
      : `> This handoff was generated automatically because the context window reached **${pct}% capacity**.`,
    `> Start a fresh session and include this note so the agent can pick up where you left off.`,
    "",
    "## Session context",
    "",
    `| Field | Value |`,
    `|---|---|`,
    `| Role | \`${role}\` |`,
    `| Task | ${task} |`,
    `| Provider | ${provider} |`,
    `| Model | ${model} |`,
    `| Tokens used | ${totalFmt} / ${limitFmt} (${pct}%) |`,
    "",
    "## What was accomplished (last 5 decisions)",
    "",
    decisionLines,
    "",
    "## Prompt for your new session",
    "",
    "Paste this at the start of your next `agent-contract run` or conversation:",
    "",
    "```",
    `I am continuing a previous agent-contract session. Context window was at ${pct}%.`,
    `Role: ${role}`,
    `Task: ${task}`,
    ``,
    `Previous decisions are logged in .agent/memory/decisions.jsonl.`,
    `Pick up from where we left off and do not repeat completed work.`,
    "```",
    "",
    `---`,
    `_Generated by agent-contract token manager at ${ts}_`,
    "",
  ].join("\n");
}

function writeHandoffScript() {
  return `#!/usr/bin/env bash
# write-handoff.sh — auto-writes a session handoff note at turn end.
# Wired to the Claude Code Stop hook via .claude/settings.json.
# Non-blocking: the Stop hook ignores the exit code.
set -uo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"
MEMORY_DIR="$ROOT/memory"
SESSION_DIR="$ROOT/session"

mkdir -p "$MEMORY_DIR" "$SESSION_DIR"

ROLE="unknown"
if [[ -f "$SESSION_DIR/active-role.txt" ]]; then
  ROLE=$(tr -d '[:space:]' < "$SESSION_DIR/active-role.txt")
fi

DECISIONS="(no decisions logged this session)"
if [[ -f "$MEMORY_DIR/decisions.jsonl" ]]; then
  d=$(tail -5 "$MEMORY_DIR/decisions.jsonl" 2>/dev/null || true)
  [[ -n "$d" ]] && DECISIONS="$d"
fi

CHANGED=""
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  c=$(git -C "$PROJECT_ROOT" diff --name-only HEAD 2>/dev/null || true)
  if [[ -z "$c" ]]; then
    c=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || true)
  fi
  [[ -n "$c" ]] && CHANGED="$c"
fi

# Skip write when nothing changed — avoids noise on trivial turns
[[ -z "$CHANGED" ]] && exit 0
CHANGED_DISPLAY="$CHANGED"

TS=$(date +%Y-%m-%d-%H%M%S 2>/dev/null || echo "ts")
OUTFILE="$MEMORY_DIR/handoff-done-\${TS}.md"

{
  printf '# Agent Handoff — %s\\n\\n' "$TS"
  printf '> Auto-generated by agent-contract Stop hook.\\n'
  printf '> Boot next session: .agent/memory/codebase-map.md → .agent/roles/%s.yaml → this file.\\n\\n' "$ROLE"
  printf '## Role\\n%s\\n\\n' "$ROLE"
  printf '## Files Changed\\n%s\\n\\n' "$CHANGED_DISPLAY"
  printf '## Last 5 Decisions\\n%s\\n\\n' "$DECISIONS"
  printf '## Resume Prompt\\n\\n\`\`\`\\nContinuing from handoff %s. Role: %s.\\nRead .agent/memory/codebase-map.md and .agent/memory/decisions.jsonl before proceeding.\\n\`\`\`\\n' "$TS" "$ROLE"
} > "$OUTFILE"

printf 'write-handoff: saved → .agent/memory/handoff-done-%s.md\\n' "$TS" >&2
exit 0
`;
}

function scopeCheckScript() {
  return `#!/usr/bin/env bash
# scope-check.sh — PreToolUse hook for Claude Code.
# Reads tool call JSON from stdin, checks if the target file falls within
# the active role's declared scope. Exits non-zero to BLOCK the tool call.
# Registered automatically in .claude/settings.json by \`agent-contract init\`.
set -uo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"
SESSION_DIR="$ROOT/session"

# Read tool input JSON from stdin (Claude Code sends this for PreToolUse hooks)
TOOL_INPUT=$(cat 2>/dev/null || true)
[[ -z "$TOOL_INPUT" ]] && exit 0

# Extract file_path from tool input JSON (handles Write, Edit, MultiEdit)
FILE_PATH=$(printf '%s' "$TOOL_INPUT" | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | grep -oE '"[^"]*"$' | tr -d '"' 2>/dev/null || true)
[[ -z "$FILE_PATH" ]] && exit 0

# Make path relative to project root
REL_PATH="\${FILE_PATH#$PROJECT_ROOT/}"
# If path still absolute (didn't start with project root), skip
[[ "$REL_PATH" = /* ]] && exit 0

# Always allow writes to contract infrastructure (.agent/memory, .agent/session, etc.)
case "$REL_PATH" in .agent/*) exit 0 ;; esac

# Fail-closed: no active role declared → block all non-contract source writes.
# The model must write its role to .agent/session/active-role.txt (boot sequence step 6)
# before it can edit any source file. Contract infra (.agent/**) is always writable above.
if [[ ! -f "$SESSION_DIR/active-role.txt" ]]; then
  printf 'scope-check: BLOCKED — no active role declared.\\n' >&2
  printf '  Write your role to .agent/session/active-role.txt before editing source files.\\n' >&2
  printf '  Example: echo "generator" > .agent/session/active-role.txt\\n' >&2
  printf '  Valid roles: generator integrator tester debugger documenter security\\n' >&2
  exit 1
fi

ROLE=$(tr -d '[:space:]' < "$SESSION_DIR/active-role.txt")
ROLE_FILE="$ROOT/roles/\${ROLE}.yaml"
[[ -f "$ROLE_FILE" ]] || exit 0

# Parse may_create and may_modify patterns from role YAML
allowed=()
in_scope_block=0
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*(may_create|may_modify)[[:space:]]*: ]]; then
    [[ "$line" =~ \\[\\] ]] && { in_scope_block=0; continue; }
    in_scope_block=1; continue
  fi
  if [[ $in_scope_block -eq 1 ]]; then
    if [[ "$line" =~ ^[[:space:]]*-[[:space:]]+(.+) ]]; then
      p="\${BASH_REMATCH[1]//\\\"/}"
      allowed+=("$p")
    else
      in_scope_block=0
    fi
  fi
done < "$ROLE_FILE"

# No scope restrictions declared — pass
(( \${#allowed[@]} == 0 )) && exit 0

# Check file against allowed patterns
for pattern in "\${allowed[@]}"; do
  case "$REL_PATH" in $pattern) exit 0 ;; esac
done

printf 'scope-check: BLOCKED — role %s cannot write: %s\\n' "$ROLE" "$REL_PATH" >&2
printf '  Allowed: %s\\n' "\${allowed[*]}" >&2
printf '  To override: update .agent/session/active-role.txt or expand .agent/roles/%s.yaml\\n' "$ROLE" >&2
exit 1
`;
}

module.exports = {
  manifestYaml,
  stackYaml,
  conventionsYaml,
  conventionsDraftYaml,
  configYaml,
  roleYaml,
  handoffNote,
  handoffTemplate,
  preGenerateCheck,
  postGenerateCheck,
  debugScopeCheck,
  securityAuditCheck,
  writeHandoffScript,
  scopeCheckScript,
  commitTemplate,
  prTemplate,
  debugReportTemplate,
  readmeForAgentDir,
  shimContent,
  decisionsHeader,
};
