"use strict";

const { stringify } = require("./yaml");

function manifestYaml() {
  return stringify({
    schema: "agent-contract/v1",
    version: "0.1.0",
    project: {
      stack: "./stack.yaml",
      conventions: "./conventions.yaml",
    },
    roles: [
      "./roles/generator.yaml",
      "./roles/integrator.yaml",
      "./roles/tester.yaml",
      "./roles/debugger.yaml",
      "./roles/documenter.yaml",
    ],
    checks: {
      pre_generate: "./checks/pre-generate.sh",
      post_generate: "./checks/post-generate.sh",
      debug_scope: "./checks/debug-scope.sh",
    },
    templates: {
      commit: "./templates/commit.txt",
      pr: "./templates/pr.md",
      debug_report: "./templates/debug-report.md",
    },
    memory: {
      decisions: "./memory/decisions.jsonl",
    },
    enforcement: {
      checks_live_in: ["pre_post_hooks", "ci"],
      scope_violation_policy: "hard_fail",
    },
  });
}

function stackYaml(detection) {
  const body = {
    schema: "agent-contract/v1",
    generated_by: "agent-contract detect",
    confidence: detection.confidence,
    language: detection.language,
    runtime: detection.runtime,
    framework: detection.framework,
    package_manager: detection.package_manager,
    test_runner: detection.test_runner,
    build: detection.build,
    lint: detection.lint,
    formatter: detection.formatter,
    db: detection.db,
    orm: detection.orm,
    entry_points: detection.entry_points || [],
    unresolved: detection.unresolved || [],
    evidence: detection.evidence || [],
  };
  const header =
    "# stack.yaml — generated by `agent-contract`.\n" +
    "# Edit the values; re-running detect will preserve manual overrides if you mark them.\n" +
    "# Fields under `unresolved` could not be auto-detected and SHOULD be filled in.\n\n";
  return header + stringify(body);
}

function conventionsYaml() {
  return (
    "# conventions.yaml — declarative engineering policy.\n" +
    "# Every entry here should map to an executable check. If you can't enforce it, it doesn't belong here.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      module_size: {
        max_lines_per_file: 300,
        max_lines_per_function: 40,
        max_params: 4,
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: {
        style: "typed_exceptions",
        bubbling: "explicit",
      },
      dependencies: {
        injection: "constructor",
        new_packages: "requires_human_approval",
      },
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 5,
      },
    })
  );
}

function roleYaml(name) {
  const roles = {
    generator: {
      schema: "agent-contract/v1",
      role: "generator",
      scope: {
        may_create: ["src/**", "tests/**"],
        may_modify: [],
        may_delete: [],
      },
      inputs_required: ["feature_name", "input_shape", "output_shape", "error_cases"],
      on_missing_input: "ask",
      output: {
        must_include: ["implementation", "unit_tests"],
        must_pass: ["lint", "typecheck", "post_generate_check"],
      },
      handoff_to: "integrator",
    },
    integrator: {
      schema: "agent-contract/v1",
      role: "integrator",
      scope: {
        may_create: [],
        may_modify: ["src/**"],
        may_delete: [],
      },
      responsibility: "wire generated modules into existing app; no business logic changes",
      on_conflict: "ask",
      handoff_to: "tester",
    },
    tester: {
      schema: "agent-contract/v1",
      role: "tester",
      scope: {
        may_create: ["tests/**"],
        may_modify: ["tests/**"],
        may_delete: [],
      },
      responsibility: "add tests for uncovered paths surfaced by integrator; never modify src/",
      handoff_to: "documenter",
    },
    debugger: {
      schema: "agent-contract/v1",
      role: "debugger",
      workflow: [
        "reproduce",
        "diagnose",
        "list_affected_files",
        "propose_solutions",
        "await_human_selection",
        "implement_within_scope",
      ],
      proposals: { min: 2, max: 4 },
      scope_rule: "changes_must_be_subset_of_diagnosis_files",
      refactor_policy: "forbidden_unless_explicitly_approved",
      on_ambiguity: "ask",
      output_template: "../templates/debug-report.md",
    },
    documenter: {
      schema: "agent-contract/v1",
      role: "documenter",
      scope: {
        may_create: ["docs/**", "README.md"],
        may_modify: ["docs/**", "README.md"],
        may_delete: [],
      },
      responsibility: "update docs to reflect merged changes; never touch source or tests",
    },
  };
  return stringify(roles[name]);
}

function preGenerateCheck() {
  return `#!/usr/bin/env bash
# pre-generate.sh — gate before the generator runs.
# Hard fails if required inputs are missing.
# Usage: pre-generate.sh <task-spec.json>
set -euo pipefail

SPEC="\${1:-}"
if [[ -z "$SPEC" || ! -f "$SPEC" ]]; then
  echo "pre-generate: missing task spec file" >&2
  exit 2
fi

required=(feature_name input_shape output_shape error_cases)
missing=()
for k in "\${required[@]}"; do
  if ! grep -q "\\"$k\\"" "$SPEC"; then
    missing+=("$k")
  fi
done

if (( \${#missing[@]} > 0 )); then
  echo "pre-generate: HARD FAIL — missing required fields: \${missing[*]}" >&2
  echo "agent must ask the human for these before proceeding." >&2
  exit 1
fi

echo "pre-generate: OK"
`;
}

function postGenerateCheck() {
  return `#!/usr/bin/env bash
# post-generate.sh — runs after the generator emits files.
# Hard fails on lint/typecheck/test violations, scope violations, or oversized files.
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"

# Scope check: diff must be within generator's allowed paths.
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  changed=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || git -C "$PROJECT_ROOT" diff --name-only)
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    case "$f" in
      src/*|tests/*) ;;
      *)
        echo "post-generate: HARD FAIL — file outside generator scope: $f" >&2
        exit 1
        ;;
    esac
  done <<< "$changed"
fi

# Size check (max 300 LOC per file under src/).
if [[ -d "$PROJECT_ROOT/src" ]]; then
  while IFS= read -r f; do
    lines=$(wc -l < "$f")
    if (( lines > 300 )); then
      echo "post-generate: HARD FAIL — $f exceeds 300 lines ($lines)" >&2
      exit 1
    fi
  done < <(find "$PROJECT_ROOT/src" -type f \\( -name "*.ts" -o -name "*.js" -o -name "*.php" -o -name "*.py" -o -name "*.go" \\))
fi

echo "post-generate: OK"
`;
}

function debugScopeCheck() {
  return `#!/usr/bin/env bash
# debug-scope.sh — enforces "fix, don't refactor" rule.
# Compares proposed changes against the file list in the debug report.
# Hard fails if changes touch files outside the diagnosed scope.
set -euo pipefail

REPORT="\${1:-}"
if [[ -z "$REPORT" || ! -f "$REPORT" ]]; then
  echo "debug-scope: missing debug report" >&2
  exit 2
fi

# Extract files listed under "## Affected Files" in the report.
declared=$(awk '
  /^## Affected Files/ { in_section=1; next }
  /^## / && in_section { in_section=0 }
  in_section && /^- / { print substr($0, 3) }
' "$REPORT" | sed 's/:.*//')

if [[ -z "$declared" ]]; then
  echo "debug-scope: HARD FAIL — no affected files declared in report" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
changed=$(git -C "$PROJECT_ROOT" diff --name-only 2>/dev/null || true)

violations=()
while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  if ! grep -qxF "$f" <<< "$declared"; then
    violations+=("$f")
  fi
done <<< "$changed"

if (( \${#violations[@]} > 0 )); then
  echo "debug-scope: HARD FAIL — changes outside diagnosed scope:" >&2
  printf '  %s\\n' "\${violations[@]}" >&2
  echo "Either expand the diagnosis (and re-justify) or remove these changes." >&2
  exit 1
fi

echo "debug-scope: OK"
`;
}

function commitTemplate() {
  return `<type>(<scope>): <subject>

<body>

Refs: <ticket>
Agent: <role> via agent-contract
`;
}

function prTemplate() {
  return `## What changed

<one-paragraph summary>

## Why

<link to ticket, decision log entry, or context>

## Scope

- [ ] Changes confined to declared scope
- [ ] No new dependencies (or: dependency approved in decisions.jsonl)
- [ ] No schema changes (or: migration included)

## Checks

- [ ] pre-generate / debug-scope passed
- [ ] post-generate passed
- [ ] Tests added / updated
- [ ] Docs updated if behavior changed

## Decision trail

<paste the relevant decisions.jsonl entry, if any>
`;
}

function debugReportTemplate() {
  return `# Debug Report

## Symptom
<observed behavior, exact error, conditions to reproduce>

## Reproduction
1.
2.

## Diagnosis
<root cause in plain language; reference specific lines>

## Affected Files
- path/to/file.ts:42-58
- path/to/other.ts:10-22

## Proposed Solutions
1. **<short label>** — <description>. Trade-off: <what it costs>.
2. **<short label>** — <description>. Trade-off: <what it costs>.

## Selected Solution
<filled in after human selects; the agent must wait>

## Implementation Notes
<filled in during implementation; must stay within Affected Files>
`;
}

function readmeForAgentDir() {
  return `# .agent/

Deterministic contract layer for coding agents. This directory is the **single source of truth** for how AI agents operate in this repository.

Any agent (Claude, Codex, Copilot, Antigravity, etc.) entering this repo MUST:

1. Read \`manifest.yaml\` first.
2. Load \`stack.yaml\` to understand the technology context.
3. Load \`conventions.yaml\` to understand engineering rules.
4. Load the relevant role from \`roles/\` for the current task.
5. Run the appropriate check from \`checks/\` before and after generating output.
6. Append non-trivial decisions to \`memory/decisions.jsonl\`.

Humans: see \`conventions.yaml\` to change policy. Re-run \`agent-contract init\` after dependency changes to refresh \`stack.yaml\`.
`;
}

function shimContent() {
  return `<!-- agent-contract:shim -->
This repository uses an agent contract. Before taking any action:

1. Read \`.agent/manifest.yaml\`.
2. Follow the role-scoped instructions in \`.agent/roles/\`.
3. Run checks in \`.agent/checks/\` and respect hard failures.
4. Log non-trivial decisions to \`.agent/memory/decisions.jsonl\`.

Scope violations are hard-failed. When inputs are missing, ask the human — do not assume.
<!-- /agent-contract:shim -->
`;
}

function decisionsHeader() {
  // JSONL files start empty; we put a comment-style first line that JSON parsers will skip
  // because consumers should read line-by-line and skip non-JSON lines.
  return "";
}

module.exports = {
  manifestYaml,
  stackYaml,
  conventionsYaml,
  roleYaml,
  preGenerateCheck,
  postGenerateCheck,
  debugScopeCheck,
  commitTemplate,
  prTemplate,
  debugReportTemplate,
  readmeForAgentDir,
  shimContent,
  decisionsHeader,
};
