"use strict";

const { stringify } = require("./yaml");

function manifestYaml(persona) {
  return stringify({
    schema: "agent-contract/v1",
    version: "0.1.0",
    persona: persona || "pragmatist",
    project: {
      stack: "./stack.yaml",
      conventions: "./conventions.yaml",
    },
    roles: [
      "./roles/generator.yaml",
      "./roles/integrator.yaml",
      "./roles/tester.yaml",
      "./roles/debugger.yaml",
      "./roles/documenter.yaml",
    ],
    checks: {
      pre_generate: "./checks/pre-generate.sh",
      post_generate: "./checks/post-generate.sh",
      debug_scope: "./checks/debug-scope.sh",
    },
    templates: {
      commit: "./templates/commit.txt",
      pr: "./templates/pr.md",
      debug_report: "./templates/debug-report.md",
    },
    memory: {
      decisions: "./memory/decisions.jsonl",
    },
    enforcement: {
      checks_live_in: ["pre_post_hooks", "ci"],
      scope_violation_policy: "hard_fail",
    },
  });
}

function stackYaml(detection) {
  const body = {
    schema: "agent-contract/v1",
    generated_by: "agent-contract detect",
    confidence: detection.confidence,
    language: detection.language,
    runtime: detection.runtime,
    framework: detection.framework,
    package_manager: detection.package_manager,
    test_runner: detection.test_runner,
    build: detection.build,
    lint: detection.lint,
    formatter: detection.formatter,
    db: detection.db,
    orm: detection.orm,
    entry_points: detection.entry_points || [],
    commands: detection.commands || null,
    unresolved: detection.unresolved || [],
    evidence: detection.evidence || [],
  };
  const header =
    "# stack.yaml — generated by `agent-contract`.\n" +
    "# Edit the values; re-running detect will preserve manual overrides if you mark them.\n" +
    "# Fields under `unresolved` could not be auto-detected and SHOULD be filled in.\n\n";
  return header + stringify(body);
}

const PRESETS = {
  "oop-strict": () =>
    "# conventions.yaml — preset: oop-strict\n" +
    "# Strict OOP: constructor injection, typed exceptions, 80% coverage floor.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      module_size: { max_lines_per_file: 250, max_lines_per_function: 30, max_params: 4 },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["service_layer", "controller_layer", "repository_layer"],
        style: "arrange_act_assert",
        min_coverage: 80,
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 3,
      },
    }),

  "functional-pragmatic": () =>
    "# conventions.yaml — preset: functional-pragmatic\n" +
    "# Function-first: minimal classes, pragmatic testing, looser thresholds.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "functional",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 50, max_params: 5 },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "allowed_in_query_modules",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "function_params", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["business_logic", "api_handlers"],
        style: "arrange_act_assert",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
        ],
        n_files_threshold: 5,
      },
    }),

  "nestjs-clean-architecture": () =>
    "# conventions.yaml — preset: nestjs-clean-architecture\n" +
    "# NestJS: module/service/controller layering, DTOs, constructor DI, pipes for validation.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      framework_notes: "nestjs — modules own their domain; cross-domain via events or shared library",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 40, max_params: 4 },
      layers: {
        controller: "http boundary only — no business logic",
        service: "business logic — no direct DB access",
        repository: "data access only — no business logic",
        dto: "required for all controller inputs and service outputs",
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      validation: "class-validator pipes on all controller inputs",
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
        mocking: "jest.mock for external services; real DB for repository tests",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
          "cross_module_dependency",
        ],
        n_files_threshold: 5,
      },
    }),

  "laravel-service-pattern": () =>
    "# conventions.yaml — preset: laravel-service-pattern\n" +
    "# Laravel: thin controllers → service layer → Eloquent repositories. FormRequests for validation.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      framework_notes: "laravel — follow service pattern; keep controllers thin",
      module_size: { max_lines_per_file: 300, max_lines_per_function: 40, max_params: 4 },
      layers: {
        controller: "delegates to service — no business logic, no direct model queries",
        service: "business logic — uses repositories or models",
        form_request: "required for all mutating controller inputs",
        model: "Eloquent only — no business logic in models",
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
        orm: "eloquent",
      },
      errors: { style: "typed_exceptions", bubbling: "explicit" },
      dependencies: { injection: "constructor", new_packages: "requires_human_approval" },
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
        mocking: "Mockery for external services; RefreshDatabase for feature tests",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 5,
      },
    }),
};

const PERSONA_TONES = {
  architect: {
    style: "deliberate",
    ask_before_building: "always",
    documentation: "required_for_every_decision",
    prohibitions: ["ship_without_design_note", "vague_task_definitions", "shortcuts_under_time_pressure"],
  },
  vibecoder: {
    style: "fast",
    ask_before_building: "only_when_blocked",
    documentation: "inline_only",
    prohibitions: ["over_engineering", "premature_abstraction", "waiting_for_perfect_spec"],
  },
  lead: {
    style: "mentorship",
    ask_before_building: "when_design_unclear",
    documentation: "explain_the_why",
    prohibitions: ["silent_decisions", "undocumented_patterns"],
  },
  pragmatist: {
    style: "balanced",
    ask_before_building: "when_spec_is_incomplete",
    documentation: "as_needed",
    prohibitions: [],
  },
};

function conventionsYaml(preset, persona) {
  const tone = PERSONA_TONES[persona] || PERSONA_TONES.pragmatist;
  if (preset && PRESETS[preset]) {
    // Inject tone block into preset output by appending it as YAML
    return PRESETS[preset]() + "\n" + stringify({ tone });
  }
  return (
    "# conventions.yaml — declarative engineering policy.\n" +
    "# Every entry here should map to an executable check. If you can't enforce it, it doesn't belong here.\n\n" +
    stringify({
      schema: "agent-contract/v1",
      paradigm: "oop",
      tone,
      module_size: {
        max_lines_per_file: 300,
        max_lines_per_function: 40,
        max_params: 4,
      },
      db: {
        transactions: "required_for_multi_write",
        migrations: "required_for_schema_change",
        raw_queries: "forbidden_outside_repository_layer",
      },
      errors: {
        style: "typed_exceptions",
        bubbling: "explicit",
      },
      dependencies: {
        injection: "constructor",
        new_packages: "requires_human_approval",
      },
      testing: {
        required_for: ["service_layer", "controller_layer"],
        style: "arrange_act_assert",
      },
      clarification: {
        ask_when: [
          "spec_missing_input_shape",
          "spec_missing_error_behavior",
          "touching_more_than_n_files",
          "new_external_dependency",
          "schema_change",
        ],
        n_files_threshold: 5,
      },
    })
  );
}

const PERSONA_GUIDANCE = {
  architect: {
    generator: [
      "document the design decision before writing code",
      "refuse tasks where input_shape or output_shape is undefined",
      "prefer named abstractions over anonymous lambdas or inline logic",
    ],
    debugger: [
      "trace the root cause before proposing any fix",
      "document all assumptions in the debug report",
      "if the fix touches more than 3 files, escalate to human review",
    ],
  },
  vibecoder: {
    generator: [
      "ship working code first; iterate on structure later",
      "ask questions via code — write a prototype, not a requirements doc",
      "prefer the simplest thing that could possibly work",
    ],
    debugger: [
      "try the obvious fix first; if it works, ship it",
      "keep debug reports minimal — just the fix and a one-liner explanation",
    ],
  },
  lead: {
    generator: [
      "explain the design choice in a comment on every non-obvious abstraction",
      "link to the pattern or principle that motivates each structural decision",
      "write code that a junior engineer can read without asking you",
    ],
    debugger: [
      "explain the bug in plain English before writing any code",
      "leave a note in the code explaining what caused this so the team learns",
    ],
  },
  pragmatist: {
    generator: [],
    debugger: [],
  },
};

function roleYaml(name, persona) {
  const guidance = (PERSONA_GUIDANCE[persona] || PERSONA_GUIDANCE.pragmatist)[name] || [];
  const roles = {
    generator: {
      schema: "agent-contract/v1",
      role: "generator",
      persona: persona || "pragmatist",
      scope: {
        may_create: ["src/**", "tests/**"],
        may_modify: [],
        may_delete: [],
      },
      inputs_required: ["feature_name", "input_shape", "output_shape", "error_cases"],
      on_missing_input: "ask",
      output: {
        must_include: ["implementation", "unit_tests"],
        must_pass: ["lint", "typecheck", "post_generate_check"],
      },
      ...(guidance.length > 0 && { guidance }),
      handoff_to: "integrator",
    },
    integrator: {
      schema: "agent-contract/v1",
      role: "integrator",
      scope: {
        may_create: [],
        may_modify: ["src/**"],
        may_delete: [],
      },
      responsibility: "wire generated modules into existing app; no business logic changes",
      on_conflict: "ask",
      handoff_to: "tester",
    },
    tester: {
      schema: "agent-contract/v1",
      role: "tester",
      scope: {
        may_create: ["tests/**"],
        may_modify: ["tests/**"],
        may_delete: [],
      },
      responsibility: "add tests for uncovered paths surfaced by integrator; never modify src/",
      handoff_to: "documenter",
    },
    debugger: {
      schema: "agent-contract/v1",
      role: "debugger",
      persona: persona || "pragmatist",
      workflow: [
        "reproduce",
        "diagnose",
        "list_affected_files",
        "propose_solutions",
        "await_human_selection",
        "implement_within_scope",
      ],
      proposals: { min: 2, max: 4 },
      scope_rule: "changes_must_be_subset_of_diagnosis_files",
      refactor_policy: "forbidden_unless_explicitly_approved",
      on_ambiguity: "ask",
      ...(guidance.length > 0 && { guidance }),
      output_template: "../templates/debug-report.md",
    },
    documenter: {
      schema: "agent-contract/v1",
      role: "documenter",
      scope: {
        may_create: ["docs/**", "README.md"],
        may_modify: ["docs/**", "README.md"],
        may_delete: [],
      },
      responsibility: "update docs to reflect merged changes; never touch source or tests",
    },
  };
  return stringify(roles[name]);
}

function preGenerateCheck() {
  return `#!/usr/bin/env bash
# pre-generate.sh — gate before the generator runs.
# Hard fails if required inputs are missing.
# Usage: pre-generate.sh <task-spec.json>
set -euo pipefail

SPEC="\${1:-}"
if [[ -z "$SPEC" || ! -f "$SPEC" ]]; then
  echo "pre-generate: missing task spec file" >&2
  exit 2
fi

required=(feature_name input_shape output_shape error_cases)
missing=()
for k in "\${required[@]}"; do
  if ! grep -q "\\"$k\\"" "$SPEC"; then
    missing+=("$k")
  fi
done

if (( \${#missing[@]} > 0 )); then
  echo "pre-generate: HARD FAIL — missing required fields: \${missing[*]}" >&2
  echo "agent must ask the human for these before proceeding." >&2
  exit 1
fi

echo "pre-generate: OK"
`;
}

function postGenerateCheck(detection) {
  const stackChecks = buildStackChecks(detection);
  return `#!/usr/bin/env bash
# post-generate.sh — runs after the generator emits files.
# Checks: scope, size${stackChecks ? ", lint, typecheck, tests" : ""}.
# Hard fails on any violation.
set -euo pipefail

ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/.." && pwd)"
PROJECT_ROOT="$(cd "$ROOT/.." && pwd)"

# Gather changed files (empty when not a git repo)
changed=""
if [[ -d "$PROJECT_ROOT/.git" ]]; then
  changed=$(git -C "$PROJECT_ROOT" diff --name-only --cached 2>/dev/null || git -C "$PROJECT_ROOT" diff --name-only || true)
fi

# Scope check: diff must be within generator's allowed paths.
if [[ -n "$changed" ]]; then
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    case "$f" in
      src/*|tests/*) ;;
      *)
        echo "post-generate: HARD FAIL — file outside generator scope: $f" >&2
        exit 1
        ;;
    esac
  done <<< "$changed"
fi

# Size check (max 300 LOC per file under src/).
if [[ -d "$PROJECT_ROOT/src" ]]; then
  while IFS= read -r f; do
    lines=$(wc -l < "$f")
    if (( lines > 300 )); then
      echo "post-generate: HARD FAIL — $f exceeds 300 lines ($lines)" >&2
      exit 1
    fi
  done < <(find "$PROJECT_ROOT/src" -type f \\( -name "*.ts" -o -name "*.js" -o -name "*.php" -o -name "*.py" -o -name "*.go" \\))
fi
${stackChecks}
echo "post-generate: OK"
`;
}

function buildStackChecks(detection) {
  if (!detection || !detection.commands) return "";
  const { commands } = detection;
  const parts = [];

  parts.push('\ncd "$PROJECT_ROOT"');

  if (commands.lint && commands.lint_ext) {
    const pat = commands.lint_ext.map((e) => `*${e}`).join("|");
    parts.push(
      `\n# Lint (${detection.lint})`,
      "lint_files=\"\"",
      "while IFS= read -r f; do",
      `  case "$f" in ${pat}) lint_files="$lint_files $f" ;; esac`,
      `done <<< "\${changed:-}"`,
      "if [[ -n \"$lint_files\" ]]; then",
      `  ${commands.lint} $lint_files || { echo "post-generate: HARD FAIL — lint (${detection.lint})" >&2; exit 1; }`,
      "fi",
    );
  }

  if (commands.typecheck) {
    parts.push(
      `\n# Typecheck (${detection.language})`,
      `${commands.typecheck} || { echo "post-generate: HARD FAIL — typecheck" >&2; exit 1; }`,
    );
  }

  if (commands.test) {
    if (commands.test_files && commands.lint_ext) {
      const pat = commands.lint_ext.map((e) => `*${e}`).join("|");
      parts.push(
        `\n# Tests (${detection.test_runner} — changed files only)`,
        "test_files=\"\"",
        "while IFS= read -r f; do",
        `  case "$f" in ${pat}) test_files="$test_files $f" ;; esac`,
        `done <<< "\${changed:-}"`,
        "if [[ -n \"$test_files\" ]]; then",
        `  ${commands.test} $test_files || { echo "post-generate: HARD FAIL — tests (${detection.test_runner})" >&2; exit 1; }`,
        "fi",
      );
    } else {
      parts.push(
        `\n# Tests (${detection.test_runner})`,
        `${commands.test} || { echo "post-generate: HARD FAIL — tests (${detection.test_runner})" >&2; exit 1; }`,
      );
    }
  }

  return parts.join("\n");
}

function debugScopeCheck() {
  return `#!/usr/bin/env bash
# debug-scope.sh — enforces "fix, don't refactor" rule.
# Compares proposed changes against the file list in the debug report.
# Hard fails if changes touch files outside the diagnosed scope.
set -euo pipefail

REPORT="\${1:-}"
if [[ -z "$REPORT" || ! -f "$REPORT" ]]; then
  echo "debug-scope: missing debug report" >&2
  exit 2
fi

# Extract files listed under "## Affected Files" in the report.
declared=$(awk '
  /^## Affected Files/ { in_section=1; next }
  /^## / && in_section { in_section=0 }
  in_section && /^- / { print substr($0, 3) }
' "$REPORT" | sed 's/:.*//')

if [[ -z "$declared" ]]; then
  echo "debug-scope: HARD FAIL — no affected files declared in report" >&2
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "\${BASH_SOURCE[0]}")/../.." && pwd)"
changed=$(git -C "$PROJECT_ROOT" diff --name-only 2>/dev/null || true)

violations=()
while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  if ! grep -qxF "$f" <<< "$declared"; then
    violations+=("$f")
  fi
done <<< "$changed"

if (( \${#violations[@]} > 0 )); then
  echo "debug-scope: HARD FAIL — changes outside diagnosed scope:" >&2
  printf '  %s\\n' "\${violations[@]}" >&2
  echo "Either expand the diagnosis (and re-justify) or remove these changes." >&2
  exit 1
fi

echo "debug-scope: OK"
`;
}

function commitTemplate() {
  return `<type>(<scope>): <subject>

<body>

Refs: <ticket>
Agent: <role> via agent-contract
`;
}

function prTemplate() {
  return `## What changed

<one-paragraph summary>

## Why

<link to ticket, decision log entry, or context>

## Scope

- [ ] Changes confined to declared scope
- [ ] No new dependencies (or: dependency approved in decisions.jsonl)
- [ ] No schema changes (or: migration included)

## Checks

- [ ] pre-generate / debug-scope passed
- [ ] post-generate passed
- [ ] Tests added / updated
- [ ] Docs updated if behavior changed

## Decision trail

<paste the relevant decisions.jsonl entry, if any>
`;
}

function debugReportTemplate() {
  return `# Debug Report

## Symptom
<observed behavior, exact error, conditions to reproduce>

## Reproduction
1.
2.

## Diagnosis
<root cause in plain language; reference specific lines>

## Affected Files
- path/to/file.ts:42-58
- path/to/other.ts:10-22

## Proposed Solutions
1. **<short label>** — <description>. Trade-off: <what it costs>.
2. **<short label>** — <description>. Trade-off: <what it costs>.

## Selected Solution
<filled in after human selects; the agent must wait>

## Implementation Notes
<filled in during implementation; must stay within Affected Files>
`;
}

function readmeForAgentDir() {
  return `# .agent/

Deterministic contract layer for coding agents. This directory is the **single source of truth** for how AI agents operate in this repository.

Any agent (Claude, Codex, Copilot, Antigravity, etc.) entering this repo MUST:

1. Read \`manifest.yaml\` first.
2. Load \`stack.yaml\` to understand the technology context.
3. Load \`conventions.yaml\` to understand engineering rules.
4. Load the relevant role from \`roles/\` for the current task.
5. Run the appropriate check from \`checks/\` before and after generating output.
6. Append non-trivial decisions to \`memory/decisions.jsonl\`.

Humans: see \`conventions.yaml\` to change policy. Re-run \`agent-contract init\` after dependency changes to refresh \`stack.yaml\`.
`;
}

function shimContent() {
  return `<!-- agent-contract:shim -->
This repository uses an agent contract. Before taking any action:

1. Read \`.agent/manifest.yaml\`.
2. Follow the role-scoped instructions in \`.agent/roles/\`.
3. Run checks in \`.agent/checks/\` and respect hard failures.
4. Log non-trivial decisions to \`.agent/memory/decisions.jsonl\`.

Scope violations are hard-failed. When inputs are missing, ask the human — do not assume.
<!-- /agent-contract:shim -->
`;
}

function conventionsDraftYaml(inferences) {
  const { sample_size, style, errors, naming, tests } = inferences;
  const lines = [];

  lines.push("# conventions.draft.yaml — DRAFT generated by `agent-contract learn`.");
  lines.push(`# Sampled ${sample_size} source file(s). Review each field then merge into conventions.yaml.`);
  lines.push("# Delete this file after merging.");
  lines.push("#");
  lines.push('schema: "agent-contract/v1"');
  lines.push("");

  // Paradigm
  if (style) {
    lines.push(`# paradigm — inferred (confidence: ${style.confidence})`);
    lines.push(`# evidence: ${style.evidence.class_files} class file(s), ${style.evidence.func_files} function-only file(s)`);
    lines.push(`paradigm: ${style.paradigm}`);
  } else {
    lines.push("# paradigm — could not infer; set manually: oop | functional | mixed");
    lines.push("paradigm: oop");
  }
  lines.push("");

  lines.push("module_size:");
  lines.push("  max_lines_per_file: 300    # default — not inferred");
  lines.push("  max_lines_per_function: 40");
  lines.push("  max_params: 4");
  lines.push("");

  lines.push("db:");
  lines.push("  transactions: required_for_multi_write");
  lines.push("  migrations: required_for_schema_change");
  lines.push("  raw_queries: forbidden_outside_repository_layer");
  lines.push("");

  // Errors
  if (errors && errors.style !== "unstructured") {
    lines.push(`# errors.style — inferred (confidence: ${errors.confidence})`);
    lines.push(`# evidence: ${errors.evidence.try_catch_files} file(s) with try/catch, ${errors.evidence.custom_error_classes} custom error class(es)`);
    lines.push("errors:");
    lines.push(`  style: ${errors.style}`);
    lines.push("  bubbling: explicit");
  } else {
    lines.push("errors:");
    lines.push("  style: typed_exceptions    # default — could not infer");
    lines.push("  bubbling: explicit");
  }
  lines.push("");

  lines.push("dependencies:");
  lines.push("  injection: constructor");
  lines.push("  new_packages: requires_human_approval");
  lines.push("");

  // Testing
  if (tests) {
    lines.push(`# testing.style — inferred (confidence: ${tests.confidence})`);
    if (tests.evidence) lines.push(`# evidence: ${tests.evidence.spec_files} spec file(s) found`);
    lines.push("testing:");
    lines.push("  required_for:");
    lines.push("  - service_layer");
    lines.push("  - controller_layer");
    lines.push(`  style: ${tests.pattern}`);
  } else {
    lines.push("testing:");
    lines.push("  required_for:");
    lines.push("  - service_layer");
    lines.push("  - controller_layer");
    lines.push("  style: arrange_act_assert    # default — no test files found");
  }
  lines.push("");

  // Naming — shown as a commented suggestion since conventions.yaml has no naming key by default
  if (naming) {
    lines.push(`# naming — inferred (confidence: ${naming.confidence})`);
    const ev = Object.entries(naming.evidence).map(([k, v]) => `${k}: ${v}`).join(", ");
    lines.push(`# evidence: ${ev}`);
    lines.push("# Uncomment to enforce:");
    lines.push("# naming:");
    lines.push(`#   files: ${naming.convention}`);
    lines.push("");
  }

  lines.push("clarification:");
  lines.push("  ask_when:");
  lines.push("  - spec_missing_input_shape");
  lines.push("  - spec_missing_error_behavior");
  lines.push("  - touching_more_than_n_files");
  lines.push("  - new_external_dependency");
  lines.push("  - schema_change");
  lines.push("  n_files_threshold: 5");

  return lines.join("\n") + "\n";
}

function configYaml() {
  return [
    "# .agent/config.yaml — orchestrator configuration.",
    "# Uncomment and set values to override the defaults.",
    "#",
    "# Providers (auto-detected in this order if not set):",
    "#   anthropic   — requires ANTHROPIC_API_KEY (api.anthropic.com, billed per token)",
    "#   openai      — requires OPENAI_API_KEY (api.openai.com, billed per token)",
    "#   claude-code — uses your Claude Pro/Max subscription via the installed `claude` CLI.",
    "#                 No API key needed. Requires Claude Code to be installed.",
    "#   echo        — dry-run only; prints the assembled prompt, calls nothing.",
    "#",
    "# If none of the above is configured, auto-detection picks the first available option.",
    "#",
    "# model: override the model used by the provider (optional).",
    "#   anthropic default: claude-opus-4-7",
    "#   openai default:    gpt-4o",
    "#   claude-code:       controlled by your Claude Code settings, not this field.",
    "#",
    "# Environment variables always take precedence over this file:",
    "#   AGENT_PROVIDER, AGENT_MODEL, ANTHROPIC_API_KEY, OPENAI_API_KEY",
    "",
    "# provider: claude-code",
    "# model: claude-opus-4-7",
  ].join("\n") + "\n";
}

function decisionsHeader() {
  // JSONL files start empty; we put a comment-style first line that JSON parsers will skip
  // because consumers should read line-by-line and skip non-JSON lines.
  return "";
}

function handoffNote({ role, task, provider, model, usage, recentDecisions }) {
  const ts = new Date().toISOString();
  const { total, limit, pct } = usage;
  const totalFmt = total.toLocaleString();
  const limitFmt = limit.toLocaleString();

  const decisionLines = (recentDecisions || [])
    .slice(-5)
    .map((d) => `- [${d.ts}] ${d.role}: ${d.task} (${d.output_lines} output lines)`)
    .join("\n") || "  (no prior decisions in this session)";

  return [
    `# Agent Handoff — ${ts}`,
    "",
    `> This handoff was generated automatically because the context window reached **${pct}% capacity**.`,
    `> Start a fresh session and include this note so the agent can pick up where you left off.`,
    "",
    "## Session context",
    "",
    `| Field | Value |`,
    `|---|---|`,
    `| Role | \`${role}\` |`,
    `| Task | ${task} |`,
    `| Provider | ${provider} |`,
    `| Model | ${model} |`,
    `| Tokens used | ${totalFmt} / ${limitFmt} (${pct}%) |`,
    "",
    "## What was accomplished (last 5 decisions)",
    "",
    decisionLines,
    "",
    "## Prompt for your new session",
    "",
    "Paste this at the start of your next `agent-contract run` or conversation:",
    "",
    "```",
    `I am continuing a previous agent-contract session. Context window was at ${pct}%.`,
    `Role: ${role}`,
    `Task: ${task}`,
    ``,
    `Previous decisions are logged in .agent/memory/decisions.jsonl.`,
    `Pick up from where we left off and do not repeat completed work.`,
    "```",
    "",
    `---`,
    `_Generated by agent-contract token manager at ${ts}_`,
    "",
  ].join("\n");
}

module.exports = {
  manifestYaml,
  stackYaml,
  conventionsYaml,
  conventionsDraftYaml,
  configYaml,
  roleYaml,
  handoffNote,
  preGenerateCheck,
  postGenerateCheck,
  debugScopeCheck,
  commitTemplate,
  prTemplate,
  debugReportTemplate,
  readmeForAgentDir,
  shimContent,
  decisionsHeader,
};
